# Configure main menu and social menu
[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/RmondJone/"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/RmondJone"

[social.params]
icon = "brand-twitter"
